import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import Nav from "./components/Navbar";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${spaceGrotesk.className} antialiased `}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
